apiVersion: v1
kind: Service
metadata:
  name: nodejs_docker_service
spec:
  type: NodePort
  selector:
    app: nodejs_docker
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    nodePort: 5000
